export const COLORS = {
	PRIMARY: '',
	SECONDARY: '',
};

export const FONTS = {
	PRIMARY: 'Satisfy',
};

export const ROUTES = {
	HOME: 'HOME',
	HAT: 'HAT',
	HATS: 'HATS',
	CREATE_HAT: 'CREATE_HAT',
	ABOUT_US: 'ABOUT_US',
	PRIVACY_POLICY: 'PRIVACY_POLICY',
	TERMS_OF_SERVICE: 'TERMS_OF_SERVICE',
	SUPPORT: 'SUPPORT',
	SETTINGS: 'SETTINGS',
};
