export const COLORS = {
	PRIMARY: '#CE295E',
	SECONDARY: '#dbdb4b',
	GRAY: '#7F7F7F',
	GRAY_LIGHT: '#A6A6A6',
	GRAY_DARK: '#404040',
	WHITE: 'white',
};

export const FONTS = {
	PRIMARY: 'Satisfy',
};

export const ROUTES = {
	HOME: 'HOME',
	HAT: 'HAT',
	HATS: 'HATS',
	CREATE_HAT: 'CREATE_HAT',
	ABOUT_US: 'ABOUT_US',
	PRIVACY_POLICY: 'PRIVACY_POLICY',
	TERMS_OF_SERVICE: 'TERMS_OF_SERVICE',
	SUPPORT: 'SUPPORT',
	SETTINGS: 'SETTINGS',
	SIGN_UP: 'SIGN_UP',
	LOGIN: 'LOGIN',
	PAY: 'PAY',
};
